services:
  mysqldb:
    platform: linux/x86_64
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    user: root
    volumes:
      - my-db:/var/lib/mysql
      - ./easy_traffic_server/sample_db.sql:/docker-entrypoint-initdb.d/sample_db.sql:ro
    env_file:
      - .env
    networks:
      - easy_traffic_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    container_name: easy_traffic_server
    restart: always
    build: ./easy_traffic_server
    ports:
      - "8080:8080"  # Expose server's port 8080 to host 8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/easy_traffic_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - easy_traffic_network

  website:
    container_name: easy_traffic_website
    build: ./easy_traffic_website
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - easy_traffic_network

volumes:
  my-db:
networks:
  easy_traffic_network:
